name: multispectral-vision
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch>=2.2.0
  - torchvision>=0.17.0
  - cudatoolkit  # This will install the latest compatible version
  - numpy>=1.26.0
  - pillow>=10.2.0
  - rasterio>=1.3.9
  - pyyaml>=6.0.1
  - tqdm>=4.66.1
  - matplotlib>=3.8.0
  - tensorboard>=2.15.0
  - scikit-learn>=1.2.0
  - opencv>=4.8.0
  - pip>=23.0.0
  - pip:
    - segmentation-models-pytorch>=0.3.0
    - albumentations>=1.3.0
    - mlflow>=2.8.0
    - dvc>=3.30.0
    - hydra-core>=1.3.0
    - einops>=0.7.0
    - kornia>=0.7.0
    - wandb>=0.15.0
    - roboflow>=1.1.0
    - python-dotenv>=1.0.0