# Default configuration for multispectral vision model

experiment_name: multispectral_segmentation
seed: 42
output_dir: outputs

# Model configuration
model:
  backbone: resnet50
  output_stride: 16
  num_classes: 21
  pretrained: true
  freeze_backbone: false

# Dataset configuration
data:
  data_dir: data/
  train_split: train
  val_split: val
  test_split: test
  batch_size: 16
  num_workers: 4
  image_size: [512, 512]
  augmentation: true
  bands: 
    - red
    - green
    - blue
    - nir

# Spectral indices configuration
spectral:
  indices:
    - ndvi
    - evi
    - savi
    - ndwi
  use_as_features: true
  savi_L: 0.5  # Soil brightness correction
  evi_G: 2.5   # Gain factor
  evi_C1: 6.0  # Coefficient 1
  evi_C2: 7.5  # Coefficient 2

# Training configuration
training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  lr_scheduler: cosine
  warmup_epochs: 5
  early_stopping_patience: 10
  grad_clip: 1.0
  mixed_precision: true